intro: A sample generator

params:
  spec: 
    prompt: Include RSpec files?
    type: yesno
    default: yes

  console:
    prompt: Select console
    type: select
    list: [irb, pry]

  license: 
    prompt: Name of license file
    type: text
    default: MIT